apiVersion: "kubeflow.org/v1alpha2"
kind: "PyTorchJob"
metadata:
  name: "pytorch-gloo-hpa"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/optfit-kaggle/distributed-training:latest
              imagePullPolicy: Always
              # securityContext:
              #   privileged: true
              #   capabilities:
              #     add:
              #       - SYS_ADMIN
              # lifecycle:
              #   postStart:
              #     exec:
              #       command: ["gcsfuse", "--implicit-dirs", "-o", "nonempty", "--key-file", "/var/service-account.json", "human-protein-atlas-data", "/mnt/hpa-data"]
              #   preStop:
              #     exec:
              #       command: ["fusermount", "-u", "/mnt/hpa-data"]
              command: ["python", "-u", "train.py", "-n", "vgg16", "-d", "hpa", "-p", "True", "--train-images-path", "/hpakf-image-data/data/train_images", "--nEpochs", "1", "--batchSz", "32", "--use-cuda", "yes", "--distributed", "True"]

              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /hpakf-image-data
                  name: hpa-data
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/optfit-kaggle/distributed-training:latest
              imagePullPolicy: Always
              resources:
                limits:
                  nvidia.com/gpu: 1
              # securityContext:
              #   privileged: true
              #   capabilities:
              #     add:
              #       - SYS_ADMIN
              # lifecycle:
              #   postStart:
              #     exec:
              #       command: ["gcsfuse", "--implicit-dirs", "-o", "nonempty", "--key-file", "/var/service-account.json", "human-protein-atlas-data", "/mnt/hpa-data"]
              #   preStop:
              #     exec:
              #       command: ["fusermount", "-u", "/mnt/hpa-data"]
              command: ["python", "-u", "train.py", "-n", "vgg16", "-d", "hpa", "-p", "True", "--train-images-path", "/hpakf-image-data/data/train_images", "--nEpochs", "1", "--batchSz", "32", "--use-cuda", "yes", "--distributed", "True"]
              volumeMounts:
                - mountPath: /hpakf-image-data
                  name: hpa-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hpa-data-pd
  labels:
    failure-domain.beta.kubernetes.io/zone: us-east1-d
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: hpakf-data2
    fsType: ext4
  